server:
  port: 8001



spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: projectproonetest@gmail.com
    password: xzskxnirhmvvlpmh
    default:
      encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/a_hi?serverTimezone=UTC&characterEncoding=UTF-8
    username: ahi
    password: a1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none



openai:
  model: gpt-4
  key: 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
  url: https://api.openai.com/v1/chat/completions